### ISSUE TITLE
ifd: Bild wird nicht angezeigt

### ISSUE THREAD

**Issue by meetlisa** [potzenheimer/meetshaus#13]
http://blog.ifd-schwaben.de/blog/panthertage (Platzhalter im 2. Absatz vom Artikeltext)

**Comment by potzenheimer** [comment]
Diese Aufgabe wäre besser unter https://github.com/potzenheimer/buildout.ifd aufgehoben gewesen, aber diese zentrale Stelle geht auch.

Hab das mal recht hemdsärmelig gelöst
